### PR TITLE
whitelist or blacklist use invalid_targets tag

### PR DESCRIPTION
**Pull request by DancingSnow0517**

### CODE REVIEW

**Comment by SuperMartijn642** [comment]
Do you have any specific use case or reason for this change?

**Comment by DancingSnow0517** [comment]
I make it for my modpack, allows me to limit the ability to only bind certain block entities, ensuring that there will be no crashes caused by undiscovered issues

**Comment by DancingSnow0517** [comment]
This change will not break any previous configurations.

**Comment by SuperMartijn642** [comment]
Thank you! The config option is available in Entangled version 1.3.19.

**Pull request merged**
